# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PythonGuiGOD.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(550, 450)
        MainWindow.setMinimumSize(QtCore.QSize(550, 450))
        MainWindow.setMaximumSize(QtCore.QSize(550, 450))
        MainWindow.setBaseSize(QtCore.QSize(3, 0))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(536, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 425))
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(375, 0, 21, 171))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 180, 531, 241))
        self.output.setObjectName("output")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(260, 0, 16, 171))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 10, 151, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.data = QtWidgets.QLabel(self.layoutWidget)
        self.data.setObjectName("data")
        self.verticalLayout.addWidget(self.data)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.rightUpButton = QtWidgets.QPushButton(self.layoutWidget)
        self.rightUpButton.setObjectName("rightUpButton")
        self.verticalLayout.addWidget(self.rightUpButton)
        self.rightmidButton = QtWidgets.QPushButton(self.layoutWidget)
        self.rightmidButton.setObjectName("rightmidButton")
        self.verticalLayout.addWidget(self.rightmidButton)
        self.rightLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.rightLine.setEnabled(False)
        self.rightLine.setObjectName("rightLine")
        self.verticalLayout.addWidget(self.rightLine)
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setEnabled(False)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(280, 10, 95, 54))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.midDownButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.midDownButton.setObjectName("midDownButton")
        self.verticalLayout_2.addWidget(self.midDownButton)
        self.midUpButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.midUpButton.setObjectName("midUpButton")
        self.verticalLayout_2.addWidget(self.midUpButton)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 10, 264, 106))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.leftupButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.leftupButton.setObjectName("leftupButton")
        self.verticalLayout_3.addWidget(self.leftupButton)
        self.leftdownButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.leftdownButton.setObjectName("leftdownButton")
        self.verticalLayout_3.addWidget(self.leftdownButton)
        self.leftLine = QtWidgets.QLineEdit(self.layoutWidget2)
        self.leftLine.setEnabled(True)
        self.leftLine.setObjectName("leftLine")
        self.verticalLayout_3.addWidget(self.leftLine)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Familienbuchhaltung"))
        self.output.setText(_translate("MainWindow", "TextLabel"))
        self.data.setText(_translate("MainWindow", "TextLabel"))
        self.rightUpButton.setText(_translate("MainWindow", "Добавить члена семьи"))
        self.rightmidButton.setText(_translate("MainWindow", "Добавить запись в базу"))
        self.okButton.setText(_translate("MainWindow", "Ok"))
        self.midDownButton.setText(_translate("MainWindow", "Общее внесение"))
        self.midUpButton.setText(_translate("MainWindow", "Общий расход"))
        self.leftupButton.setText(_translate("MainWindow", "Посмотреть расход одного человека за период"))
        self.leftdownButton.setText(_translate("MainWindow", "Посмотреть внесение одного человека за период"))

